<div>
    <div id="errors" style="color: darkred;font-weight: bold;">
        <?php if($this->error): ?>       
            <?php if(isset($this->error["loginpass"])): ?>
                <?php if(isset($this->error["loginpass"]["lwmvc_2"])): ?>
                    <p>Passwort max. <?php echo $this->error["loginpass"]["lwmvc_2"]["options"]["maxlength"]; ?> Zeichen</p>
                <?php endif; ?>
                <?php if(isset($this->error["loginpass"]["lwmvc_3"])): ?>
                    <p>Passwort min. <?php echo $this->error["loginpass"]["lwmvc_3"]["options"]["minlength"]; ?> Zeichen</p>
                <?php endif; ?>
                <?php if(isset($this->error["loginpass"]["lwmvc_4"])): ?>
                    <p>Passwort Pflichtfeld</p>
                <?php endif; ?>
                <?php if(isset($this->error["loginpass"]["lwmvc_15"])): ?>
                    <p>Passwort und Passwort-Wiederholung m&uuml;ssen identisch sein</p>
                <?php endif; ?>
            <?php endif;?>        
        <?php endif; ?>
    </div>
    <form action="<?php echo $this->actionUrl; ?>" method="post">
        Passwort:&nbsp;&nbsp;&nbsp;&nbsp; <input type="password" name="loginpass" /><br>
        Passwort WDHL: <input type="password" name="loginpass2" /><br>
        <input type="submit" value="abschicken"/>
    </form>
    <div>
        <a href="<?php echo $this->loginUrl; ?>">zur&uuml;ck zum Login</a>
    </div>
</div>
