<?php if($this->useDefaultCss): ?>
<style type="text/css">
	body {
		font-family: Segoe, "Segoe UI", "DejaVu Sans", "Trebuchet MS", Verdana, sans-serif;color: #333333;
		font-size: 14px;
		line-height: 1.42857;
	}
	a {
		color: #428BCA;
		text-decoration: none;
	}
	a:hover, a:focus {
		color: rgb(42, 100, 150);
		text-decoration: underline;
	}
	a:active, a:hover {
		outline: 0px none;
	}
	form {
		margin: 0;
		padding:0;
	}
	.form-group {
		margin-bottom: 15px;
	}
	label {
		display: inline-block;
		font-weight: normal;
		margin-bottom: 5px;
	}
	button, input, select, textarea {
		font-family: inherit;
		font-size: 100%;
		margin: 0;
	}
	.form-control {
		background-color: #FFFFFF;
		border: 1px solid #CCCCCC;
		border-radius: 4px 4px 4px 4px;
		box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
		color: #555555;
		display: block;
		font-size: 14px;
		height: 34px;
		line-height: 1.42857;
		padding: 0 12px;
		transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
		vertical-align: middle;
		width: 100%;
	}
	.form-control:focus {
		border-color: rgb(102, 175, 233);
		outline: 0px none;
		box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(102, 175, 233, 0.6);
	}
	.btn {
		display: inline-block;
		padding: 6px 12px;
		margin-bottom: 0px;
		font-size: 14px;
		font-weight: normal;
		line-height: 1.42857;
		text-align: center;
		white-space: nowrap;
		vertical-align: middle;
		cursor: pointer;
		border: 1px solid transparent;
		border-radius: 4px 4px 4px 4px;
		-moz-user-select: none;
	}
	.btn-default {
		color: rgb(51, 51, 51);
		background-color: rgb(255, 255, 255);
		border-color: rgb(204, 204, 204);
	}
	.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {
		color: rgb(51, 51, 51);
		background-color: rgb(235, 235, 235);
		border-color: rgb(173, 173, 173);
	}
	.btn:hover, .btn:focus {
		color: rgb(51, 51, 51);
		text-decoration: none;
	}
	.btn:focus {
		outline: thin dotted rgb(51, 51, 51);
		outline-offset: -2px;
	}
	.width-50 {
		width:50%
	}
</style>
<?php endif; ?>
<div>
    <div id="errors" style="color: darkred;font-weight: bold;">
        <?php if($this->errors): ?>       
            <?php foreach($this->errors as $error): ?>
                <p><?php echo $error[$this->lang]; ?></p>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    
    <form action="<?php echo $this->actionUrl; ?>" method="post" role="form">
    	<div class="form-group width-50">
            <label for="loginpass">Passwort:</label>
            <input type="password" class="form-control" name="loginpass" placeholder="">
        </div>
        <div class="form-group width-50">
            <label for="loginpass2">Passwort WDHL:</label>
            <input type="password" class="form-control" name="loginpass2" placeholder="">
        </div>
  		<button type="submit" class="btn btn-default">speichern</button>
    </form>
    <?php if(!$this->useOnlyPwLost): ?>
    <div>
    	<br>
        <a href="<?php echo $this->loginUrl; ?>">zur&uuml;ck zum Login</a>
    </div>
    <?php endif; ?>
</div>
